name="Jeevan"
print(len(name))
print(name.endswith("jee"))
print(name.startswith("Jee"))
print(name.endswith("jee"))
print(name.endswith("van"))
print(name.lower())
print(name.upper())
print(name.title())
print(name.rstrip())
print(name.lstrip())
name="Jeevan"
index=name.find("eev")
print(index)
name="Jeevan"
replaced_string=name.replace("Jeevan","Basavanagowda")
print(replaced_string)